#!/usr/bin/env bash
# PreToolUse guardrail (sdlc-kit):
#   - blocks any access to real env files (.env, .env.local, .env.backup, ...). Templates named
#     .env.example are fine.
#   - blocks edits (not reads) to the project's protected paths, listed one per line in
#     .claude/protected-paths as bash glob patterns relative to the repo root, e.g.
#         vendor/*                # vendored upstream code
#         src/generated/*         # generated by `make codegen`
#     `*` matches across directories. Text after `#` is a comment, shown as the reason.
# Exit code 2 blocks the tool call and shows stderr to Claude.
set -euo pipefail

input=$(cat)
root=${CLAUDE_PROJECT_DIR:-$(git rev-parse --show-toplevel 2>/dev/null || pwd)}
tool=$(jq -r '.tool_name // empty' <<<"$input")
path=$(jq -r '.tool_input.file_path // .tool_input.notebook_path // empty' <<<"$input")
[[ -z "$path" ]] && exit 0

base=$(basename "$path")
if [[ "$base" == .env* && "$base" != ".env.example" ]]; then
  echo "Blocked: $path is a local env file with secrets. Use the matching .env.example instead, or ask the user for the value you need." >&2
  exit 2
fi

[[ "$tool" == "Read" ]] && exit 0
list="$root/.claude/protected-paths"
[[ -f "$list" ]] || exit 0

rel=${path#"$root"/}
rel=${rel#./}
while IFS= read -r line || [[ -n "$line" ]]; do
  pattern=${line%%#*}
  pattern=$(echo "$pattern" | xargs)
  [[ -z "$pattern" ]] && continue
  reason=""
  [[ "$line" == *"#"* ]] && reason=$(echo "${line#*#}" | xargs)
  # shellcheck disable=SC2053
  if [[ "$rel" == $pattern ]]; then
    echo "Blocked: $rel is a protected path (${reason:-listed in .claude/protected-paths}). Don't hand-edit it; ask the user first." >&2
    exit 2
  fi
done < "$list"

exit 0
